# Generated by Django 4.1.7 on 2023-03-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Correo electronico')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ultimo inicio de sesion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_activate', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
