# Generated by Django 4.1.7 on 2023-03-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cars',
            name='state',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Anulado', 'Anulado'), ('Comprado', 'Comprado')], default='activo', max_length=100),
        ),
    ]
