# Generated by Django 4.1.7 on 2023-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cars_price_alter_cars_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='state',
            field=models.CharField(choices=[('Comprado', 'Comprado'), ('Anulado', 'Anulado'), ('Activo', 'Activo')], default='activo', max_length=100),
        ),
    ]
