# Generated by Django 4.1.7 on 2023-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cars_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cars',
            name='state',
            field=models.CharField(choices=[('Comprado', 'Comprado'), ('Activo', 'Activo'), ('Anulado', 'Anulado')], default='activo', max_length=100),
        ),
    ]
